# Generated by Django 2.2.4 on 2020-08-14 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dojoNinjasApp', '0002_ninja_dojo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dojo',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='ninja',
            old_name='Name',
            new_name='name',
        ),
    ]
