# Generated by Django 2.2.4 on 2020-08-14 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojoNinjasApp', '0003_auto_20200814_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojo',
            name='desc',
            field=models.TextField(max_length=255, null=True),
        ),
    ]
